localrules: all_snp_cpg_annotation_overlap

# ------------------------------------------------------------------------------
# Get state overlaps for cis-meQTLs and matched background (SLURM JOB ARRAY)
# ------------------------------------------------------------------------------
rule snp_cpg_annotation_overlap_slurm:
        input:
                cosmo = "cis-cosmopairs_combined_151216.RData",
                cosmo_snps = "cosmo-snps.txt",
                cosmo_cpgs = "cosmo-cpgs.txt",
                snp_incl = "snps2include.RData",
                cpg_incl = "cpgs2include.RData",
                cpg_msd = "cpg_annotation_lolipop.rds",
                snp_freq = "allele_frequencies_kora.rds",
                snp_annot = "epigenetic_state_annotation_weighted_snps.rds",
                cpg_annot = "enrichment_epigenetic_state_weighted_annotation_all_cpgs.RData"
        output:
                matches = "chromHMM_enrichment_slurm/cis_annotation_overlap_{iter}.rds"
        threads:
                1
        resources:
                mem_mb = 6000
        params:
                samplesize = 1000,
        log:
                "logs/chromHMM_enrichment_slurm/cis_annotation_overlap_{iter}.log"
        benchmark:
                "benchmarks/chromHMM_enrichment_slurm/cis_annotation_overlap_{iter}.bmk"
        script:
                "../R/cre_enrichment/snp_cpg_annotation_overlap_batchjobs.R"

# ------------------------------------------------------------------------------
# Target rule to perform 150 iterations of the overlap/matched background
# calculations above
# ------------------------------------------------------------------------------
rule all_snp_cpg_annotation_overlap_slurm:
	input:
		expand("chromHMM_enrichment_slurm/cis_annotation_overlap_{iter}.rds", iter=range(1,151))
